name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ANCHOR_VERSION: 0.28.0
  SOLANA_VERSION: 1.17.1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Cache Cargo registry + index
        uses: actions/cache@v2
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-v0000-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly

      # - name: Install Linux dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y pkg-config build-essential libudev-dev

      # Install Solana
      - name: Cache Solana binaries
        id: solana-cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/solana
            ~/.local/share/solana/install
          key: ${{ runner.os }}-${{ env.SOLANA_VERSION }}

      - name: Install Solana
        if: steps.solana-cache.outputs.cache-hit != 'true'
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.1/install)"

      - name: Setup Solana Path
        run: |
          echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana --version
          solana config get

      - run: solana-keygen new --no-bip39-passphrase
        shell: bash

      - run: solana config set --url localhost
        shell: bash

      - name: Install Anchor
        run: yarn global add @coral-xyz/anchor-cli@${{ env.ANCHOR_VERSION }}

      - name: Run tests
        run: yarn && anchor test
