name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Reusable
    uses: ./.github/workflows/reusable-tests.yml
    with:
      cache: true
      solana_cli_version: 1.17.0
      solang_version: 0.3.2
      node_version: 18.18.0
      cargo_profile: debug
      anchor_binary_name: anchor-binary
